# simple ado pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml 

trigger: none

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo Build
    - bash: echo $(Build.BuildId)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - bash: echo $(Build.SourcesDirectory)
    - bash: ls -R $(Build.SourcesDirectory)
    - bash: echo $(Agent.BuildDirectory)
    - bash: ls -R $(Agent.BuildDirectory)
    