# simple ado pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml 

trigger: none

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo Build
    # - task: CopyFiles@2
    #   inputs:
    #     SourceFolder: '$(Build.SourcesDirectory)'
    #     Contents: |
    #         **/*.sql
    #     TargetFolder: '$(Build.ArtifactStagingDirectory)'
    # - bash: ls -R $(Build.ArtifactStagingDirectory)
    # - task: PublishBuildArtifacts@1
    #   inputs:
    #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #     ArtifactName: 'yamls'
    #     publishLocation: 'Container'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)'
        artifact: 'csvFile'
        publishLocation: 'pipeline'
        includeRootFolder: false
        contents: |
         *.sql
    
    
    