# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none


variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildPublish
  displayName: Build image and publish
  jobs:
  - job: BuildPublish
    displayName: Build image and publish
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: ls $(Build.SourcesDirectory)
    - bash: ls $(Build.StagingDirectory)
    - bash: ls $(Build.ArtifactStagingDirectory)
    - bash: ls $(Pipeline.Workspace)
    - task: Docker@2
      displayName: Build an image and push it to container registry
      inputs:
        containerRegistry: 'docker-hub'
        repository: 'bibekmantree/in28min'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
        addPipelineData: false
        addBaseImageData: false
    - bash: ls $(Build.SourcesDirectory)
    - bash: ls $(Build.StagingDirectory)
    - bash: ls $(Build.ArtifactStagingDirectory)
    - bash: ls $(Pipeline.Workspace)
